import type { Metadata } from "next";
import { Poppins, Rajdhani, Roboto } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";


const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ['400', '500', '600', '700', '800'],
  display: "swap",
});

const roboto = Roboto({
  subsets:["latin"],
  variable: "--font-roboto",
  weight: ['400'],
  display: "swap",
});

const rajdhani = Rajdhani({
  variable: "--font-rajdani",
  subsets: ["latin"],
  weight: ['400'],
  display: "swap",
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${roboto.variable} ${rajdhani.variable} antialiased`}
      >

        <Header />
        {children}
      </body>
    </html>
  );
}
